name: glu_trotter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¥ Firebase dependencies
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4  # (Ajout si besoin de stockage Firebase)

  # ðŸ“ Localisation et Cartes
  flutter_map: ^8.1.1  # MAP Flutter (alternative Ã  Google Maps)
  latlong2: ^0.9.0
  geolocator: ^13.0.2  # ðŸ”¥ Correction de la version pour Ã©viter les conflits

  # ðŸ“¸ Image & Camera
  image_picker: ^1.1.2
  mobile_scanner: ^6.0.7  # Scanner des codes-barres

  # ðŸ—“ï¸ Utilitaires
  google_sign_in: ^6.1.5
  shared_preferences: ^2.2.2  # ðŸ”¥ Mise Ã  jour
  table_calendar: ^3.0.8
  provider: ^6.1.2  # ðŸ”¥ DowngradÃ© pour Ã©viter l'erreur
  http: ^1.0.0
  audioplayers: ^6.4.0
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # ðŸ“Œ IcÃ´nes personnalisÃ©es pour l'application
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo_app.jpg
    - assets/carbonara.jpg
    - assets/cesar.jpg
    - assets/tarte.jpg
    - assets/pizza.jpg
    - assets/soupe.jpg
    - assets/boeuf.jpg
    - assets/mousse.jpg
    - assets/crepes.jpg
    - assets/music.mp3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_app.jpg"
